name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Target
      run: rustup target install thumbv7em-none-eabihf riscv32imac-unknown-none-elf riscv32imc-unknown-none-elf riscv32i-unknown-none-elf 
    - uses: actions/checkout@v1
    - name: Build - ARM
      run: cargo build --release --target=thumbv7em-none-eabihf
    - name: Build - RISCV
      run: cargo build --release --target=riscv32imac-unknown-none-elf

